# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

name: MetaSDKSample

include:
  - ../../../xcodegen_project_common.yml

options:
  deploymentTarget:
    iOS: '13'

packages:
  MetaLogin:
    path: ../../MetaSDK

targets:
  MetaSDKSample:
    platform: iOS
    type: application
    sources:
      - path: MetaSDKSample
    dependencies:
      - package: MetaLogin
    preBuildScripts:
      - name: Run Swiftlint
        showEnvVars: false
        script: ./build_phase_swiftlint.sh
    settings:
      PROVISIONING_PROFILE_SPECIFIER: "MetaSDK Sample Local Development"
      DEVELOPMENT_TEAM: V9WTTPBFK9
      FB_APP_VERSION: "1.0"
      FB_BUNDLE_VERSION: "1.0"
      FB_BUNDLE_VERSION_SHORT: "1.0"
      PRODUCT_NAME: MetaSDKSample
      PRODUCT_BUNDLE_IDENTIFIER: com.meta.MetaSDKSample.localDevelopment
      PROVISIONING_PROFILE_SPECIFIER: "MetaSDK Sample Local Development"

schemes:
  MetaSDKSample:
    build:
      targets:
        MetaSDKSample: all
    test:
      targets:
        - package: MetaLogin/MetaLoginTests
