---
author: Facebook
author_url: https://developers.facebook.com
clean: true
copyright: Copyright (c) 2016-present, Facebook, Inc. All rights reserved.
github_file_prefix: https://github.com/facebook/facebook-swift-sdk/tree/0.3.3
github_url: https://github.com/facebook/facebook-swift-sdk
hide_documentation_coverage: true
module: FacebookCore
module_version: 0.3.3
output: docs
podspec: FacebookCore.podspec
readme: README.md
skip_undocumented: true
source_directory: Sources
theme: fullwidth
use_safe_filenames: true

custom_categories:
  - children:
      - AccessToken
      - UserProfile
      - UserProfilePictureView
      - ApplicationDelegate
      - SDKSettings
      - SDKLoggingBehavior
      - SDKVersion
    name: Common
  - children:
      - AppEvent
      - AppEventName
      - AppEventParameterName
      - AppEventsLogger
      - AppEventLoggable
      - AppEventParameterValueType
    name: App Events
  - children:
      - LoginManager
      - LoginButton
      - LoginButtonDelegate
      - LoginBehavior
      - LoginDefaultAudience
      - LoginResult
    name: Facebook Login
  - children:
      - Permission
      - ReadPermission
      - PublishPermission
    name: Facebook Permissions
  - children:
      - GraphRequest
      - GraphRequestProtocol
      - GraphRequestResult
      - GraphRequestHTTPMethod
      - GraphResponse
      - GraphResponseProtocol
      - GraphRequestConnection
      - GraphRequestDataAttachment
    name: Graph API
  - children:
      - ShareButton
      - SendButton
      - LikeButton
      - LikeControl
      - LikableObject
    name: Sharing Buttons
  - children:
      - ShareDialog
      - ShareDialogMode
      - MessageDialog
      - ContentSharingDialogProtocol
    name: Sharing Dialogs
  - children:
      - LinkShareContent
      - Photo
      - PhotoShareContent
      - Video
      - VideoShareContent
      - Hashtag
      - ContentProtocol
      - ContentSharingResultProtocol
      - PostSharingResult
    name: Shareable Content
  - children:
      - OpenGraphObject
      - OpenGraphAction
      - OpenGraphShareContent
      - OpenGraphPropertyName
      - OpenGraphPropertyValue
      - OpenGraphPropertyContaining
    name: Share Custom Open Graph Stories
  - children:
      - GraphSharer
      - ShareError
      - ContentSharerResult
      - ContentSharingProtocol
    name: Sharing via Graph API
  - children:
      - AppInvite
    name: App Invites
  - children:
      - GameRequest
    name: Game Requests
  - children:
      - "==(_:_:)"
    name: Equality Helpers
