pod 'FBSDKLoginKit', '~> 8.0.0'
pod 'FBSDKCoreKit', '~> 8.0.0'
pod 'FBSDKShareKit', '~> 8.0.0'
pod 'FBSDKGamingServiceKit', '~> 8.0.0'
pod 'Firebase/Analytics'
# or pod 'Firebase/AnalyticsWithoutAdIdSupport'
# for Analytics without IDFA collection capability
