load("@fbsource//tools/build_defs/apple:bundle_config.bzl", "bundle_config")
load("@fbsource//tools/build_defs/apple:config_utils_defs.bzl", "APPLICATION_IOS_CONFIG", "fbchain_configs")
load("@fbsource//tools/build_defs/apple:fb_apple_asset_catalog.bzl", "fb_apple_asset_catalog")
load("@fbsource//tools/build_defs/apple:fb_apple_resource.bzl", "fb_apple_resource")
load("@fbsource//tools/build_defs/apple:ios_binary.bzl", "ios_binary")
load("@fbsource//tools/build_defs/apple:plist_for_facebook_apps.bzl", "plist_for_facebook_apps")

FB_APP_VERSION = "1.0"

FB_BUNDLE_VERSION_SHORT = "1.0"

BUNDLE_CONFIG = bundle_config(
    {
        "bundle_id": "com.facebook.CoffeeShop.internalDevelopment",
        "entitlements_file": "Entitlements-Local.plist",
    },
    {
        "local": {
            # Unused
            "entitlements_file": "Entitlements-InHouse.plist",
        },
        "master": {
            "entitlements_file": "Entitlements-InHouse.plist",
        },
        "production": {
            # Unused
        },
    },
)

plist_for_facebook_apps(
    name = "InfoPlist",
    build_number = BUNDLE_CONFIG.bundle_version,
    entitlements_plist = BUNDLE_CONFIG.entitlements_file,
    src_plist = "CoffeeShop/Info.plist",
)

ios_binary(
    name = "CoffeeShop",
    allow_swift = True,
    autoglob = True,
    bridging_header = "CoffeeShop/CoffeeShop-Bridging-Header.h",
    compiler_flags = [
        "-fobjc-arc",
        "-w",
        "-D BUCK",
        "-D DEBUG=1",
        "-Wunused-function",
        "-Werror",
        "-Wincomplete-implementation",
        "-Warc-performSelector-leaks",
        "-fmodules",
    ],
    frameworks = [
        "JavaScriptCore",
        "UserNotifications",
    ],
    info_plist = ":InfoPlist",
    info_plist_substitutions = fbchain_configs(
        APPLICATION_IOS_CONFIG,
        {
            "FB_BUNDLE_ID": BUNDLE_CONFIG.bundle_id,
            "FB_BUNDLE_VERSION": FB_APP_VERSION,
            "FB_BUNDLE_VERSION_SHORT": FB_BUNDLE_VERSION_SHORT,
        },
    ),
    swift_version = "5",
    url_scheme_validation_autoinit_enabled = False,
    visibility = ["PUBLIC"],
    deps = [
        ":Assets",
        ":Resources",
        "//fbobjc/ios-sdk/FBSDKCoreKit:FBSDKCoreKit",
        "//fbobjc/ios-sdk/internal/FBSDKBetaKit:FBSDKBetaKit",
        "//fbobjc/ios-sdk/internal/testing/E2EUtils:E2EUtils",
    ],
)

ios_binary(
    name = "E2E",
    autoglob = True,
    autoglob_dangerous_directory_name_override = "CoffeeShop",
    bridging_header = "CoffeeShop/CoffeeShop-Bridging-Header.h",
    compiler_flags = [
        "-fobjc-arc",
        "-w",
        "-D BUCK",
        "-D DEBUG=1",
        "-Wunused-function",
        "-Werror",
        "-Wincomplete-implementation",
        "-Warc-performSelector-leaks",
        "-fmodules",
    ],
    frameworks = [
        "JavaScriptCore",
        "UserNotifications",
    ],
    info_plist = ":InfoPlist",
    info_plist_substitutions = fbchain_configs(
        APPLICATION_IOS_CONFIG,
        {
            "FB_BUNDLE_ID": BUNDLE_CONFIG.bundle_id,
            "FB_BUNDLE_VERSION": FB_APP_VERSION,
            "FB_BUNDLE_VERSION_SHORT": FB_BUNDLE_VERSION_SHORT,
            "FacebookDomainPart": "trunkstable",
        },
    ),
    module_name = "CoffeeShop",
    swift_version = "5",
    url_scheme_validation_autoinit_enabled = False,
    visibility = ["PUBLIC"],
    deps = [
        ":Assets",
        ":Resources",
        "//fbobjc/ios-sdk/FBSDKCoreKit:FBSDKCoreKit",
        "//fbobjc/ios-sdk/internal/FBSDKBetaKit:FBSDKBetaKit",
    ],
)

fb_apple_asset_catalog(
    name = "Assets",
    app_icon = "AppIcon",
    dirs = [
        "CoffeeShop/Assets.xcassets",
    ],
)

fb_apple_resource(
    name = "Resources",
    dirs = ["CoffeeShop/Assets.xcassets"],
    files = glob([
        "CoffeeShop/Base.lproj/*",
        "CoffeeShop/*.storyboard",
    ]),
)
