# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

name: CoffeeShop

include:
  - ../../../xcodegen_project_common.yml

projectReferences:

  FBAEMKit:
    path: ../../../FBAEMKit/FBAEMKit.xcodeproj
  FBSDKCoreKit_Basics:
    path: ../../../FBSDKCoreKit_Basics/FBSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../../../FBSDKCoreKit/FBSDKCoreKit.xcodeproj
  FBSDKBetaKit:
    path: ../../FBSDKBetaKit/FBSDKBetaKit.xcodeproj
  E2EUtils:
    path: ../E2EUtils/E2EUtils.xcodeproj

targets:
  CoffeeShop:
    platform: iOS
    type: application
    sources:
      - path: Coffeeshop
        excludes:
          - Info.plist
    dependencies:
      - target: FBAEMKit/FBAEMKit-Static
        embed: false
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Static
        embed: false
      - target: FBSDKCoreKit/FBSDKCoreKit-Static
        embed: false
      - target: FBSDKBetaKit/FBSDKBetaKit
        embed: false
      - target: E2EUtils/E2EUtils
      - sdk: UserNotifications.framework
      - sdk: Accelerate.framework
      - sdk: libz.tbd
      - sdk: libc++.tbd
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: CoffeeShop/CoffeeShop-Bridging-Header.h
      CODE_SIGN_ENTITLEMENTS: Entitlements-Local.plist
      PROVISIONING_PROFILE_SPECIFIER: "CoffeeShop Local Development"
      FB_BUNDLE_VERSION: "1.0"
      FB_BUNDLE_VERSION_SHORT: "1.0"
      DEVELOPMENT_TEAM: V9WTTPBFK9
      EXECUTABLE_NAME: CoffeeShop
      PRODUCT_NAME: CoffeeShop

    compilerFlags:
      - "-fobjc-arc"
      - "-w"
      - "-D DEBUG=1"
      - "-Wunused-function"
      - "-Werror"
      - "-Wincomplete-implementation"
      - "-Warc-performSelector-leaks"
      - "-fmodules"
