#!/usr/bin/env fbpython
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import argparse
import collections
import json
import os
import pathlib
import re
import subprocess
import sys

from xcodebuild_warnings_allowlist import XCODEBUILD_WARNINGS_ALLOWLIST

# Warnings that already existed when the ratchet went in. New warnings fail the check;
# these do not, so the backlog can be paid down without blocking every diff on it.
BASELINE_FILE = "scripts/xcodebuild_warnings_baseline.txt"


def is_diagnostic_context(line: str) -> bool:
    """True for the source-context lines a compiler prints beneath a diagnostic.

    Swift echoes the offending source under each diagnostic, and the caret line repeats
    the message:

         93 |   case helpRequest(ParsableCommand.Type? = nil)
            |        `- warning: associated value 'helpRequest' ...

    Both contain "warning: " and would otherwise be recorded as warnings in their own
    right. They are not: they are a second rendering of the diagnostic immediately above.
    Counting them also makes the baseline unstable, because how much context a build
    prints varies, so the count drifts with no warning having been added or removed.
    """
    return re.match(r"^\s*(\d+\s*)?\|", line) is not None


def normalize(warning: str) -> str:
    """Reduce a warning to something stable across machines and edits.

    A raw warning line carries an absolute DerivedData path and a line:column that moves
    whenever anything above it changes, so matching on the raw text would make the
    baseline fail constantly for reasons that have nothing to do with the warning. The
    signature keeps the file and the message and drops everything that drifts.
    """
    # Strip `:120:15:` first, while the path still ends in an extension. Doing this after
    # the DerivedData substitution below would leave the line numbers of generated headers
    # in the signature, and those move every time their source changes.
    warning = re.sub(r":\d+:\d+:", ":", warning)
    # Absolute DerivedData paths differ per machine and per build.
    warning = re.sub(r"/Users/[^/]+/Library/Developer/Xcode/DerivedData/\S+?\.(h|swift|m)", "<DERIVED_DATA>", warning)
    warning = re.sub(r"/\S*?/DerivedData/\S+?\.(h|swift|m)", "<DERIVED_DATA>", warning)
    # Warnings from SDK headers carry the Xcode install path, which is /Applications on a
    # laptop and /usr/local/fbprojects/... on a build host. Collapse the prefix and keep the
    # part that identifies the header, so one baseline works in both places.
    warning = re.sub(r"\S*\.app/Contents/Developer/", "<SDK>/", warning)
    return " ".join(warning.split())


# Signature prefixes for code this repo does not compile. `normalize` rewrites Xcode/SDK
# header paths to `<SDK>/...` and generated-header paths to `<DERIVED_DATA>`.
EXTERNAL_SIGNATURE_PREFIXES = ("<SDK>", "<DERIVED_DATA>")


def is_external(signature: str) -> bool:
    """True for a warning in code outside this repo, which --prune-baseline must not drop.

    These are not ours to fix, and they do not appear in every build. The
    `SKTestTransaction.h` entry showed up in two of three consecutive CI runs against
    identical code. Pruning on a single observation would drop an entry that is still
    real, and the next diff to touch anything would fail on a warning nobody introduced.

    Warnings in repo files do not have that problem: if the file compiles, its warnings
    are deterministic, so absence from a run means someone fixed it.
    """
    return signature.startswith(EXTERNAL_SIGNATURE_PREFIXES)


def load_baseline(base_dir: str) -> collections.Counter:
    """Signature -> how many times it was seen when the baseline was written.

    Counts matter because normalization deliberately drops line numbers, so several
    warnings in one file with the same text share a signature. Without a count, adding
    another instance of a warning that is already baselined would not register as new.
    """
    path = pathlib.Path(base_dir) / BASELINE_FILE
    counts = collections.Counter()
    if not path.is_file():
        return counts
    for line in path.read_text().splitlines():
        line = line.rstrip()
        if not line.strip() or line.startswith("#"):
            continue
        count, tab, signature = line.partition("\t")
        if tab and count.strip().isdigit():
            counts[signature] += int(count.strip())
        else:
            counts[line.strip()] += 1
    return counts


def write_baseline(base_dir: str, signatures) -> pathlib.Path:
    path = pathlib.Path(base_dir) / BASELINE_FILE
    path.write_text(
        "# Generated by scripts/check_for_xcodebuild_warnings.py --update-baseline\n"
        "#\n"
        "# Warnings that already existed when this file was written, as `count<TAB>signature`.\n"
        "# The check fails on anything not listed here, and on any signature occurring MORE\n"
        "# times than its count -- normalization drops line numbers, so several warnings in\n"
        "# one file can share a signature, and without the count a second instance of an\n"
        "# already-listed warning would slip through.\n"
        "#\n"
        "# Shrinking this file is the point. Fix warnings, then --update-baseline\n"
        "# --prune-baseline and land the smaller file. That is safe to run from a laptop:\n"
        "# pruning only drops entries in files this repo compiles.\n"
        "#\n"
        "# Entries for code we do not compile -- `<SDK>/...` and `<DERIVED_DATA>` -- are never\n"
        "# pruned, because they do not appear in every build and one run seeing none of them\n"
        "# does not mean they are gone. To retire one of those, allowlist it instead; we are\n"
        "# never going to fix a warning in Apple's headers.\n"
        "#\n"
        "# --update-baseline without --prune-baseline adds to this file rather than replacing\n"
        "# it, so it can absorb a batch of new pre-existing debt (a toolchain upgrade, say)\n"
        "# without dropping anything.\n"
        + "\n".join(f"{count}\t{signature}" for signature, count in sorted(signatures.items()))
        + "\n"
    )
    return path


def find_iphone_simulator_destination():
    """Dynamically find an available iPhone simulator instead of hardcoding a model."""
    result = subprocess.run(
        ["/usr/bin/xcrun", "simctl", "list", "--json", "devices", "available"],
        capture_output=True,
        check=False,
        encoding="utf-8",
    )
    if result.returncode != 0:
        return "iPhone 16"

    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return "iPhone 16"

    for runtime_devices in data.get("devices", {}).values():
        for device in runtime_devices:
            name = device.get("name", "")
            if name.startswith("iPhone") and "SE" not in name:
                return name

    return "iPhone 16"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="add this run's warnings to the baseline instead of failing",
    )
    parser.add_argument(
        "--prune-baseline",
        action="store_true",
        help=(
            "with --update-baseline, drop baseline entries this run did not see. Only "
            "applies to files this repo compiles; <SDK> and <DERIVED_DATA> entries are "
            "always carried over, since they do not appear in every build"
        ),
    )
    args = parser.parse_args()

    base_dir = git_base_dir() if is_git_dir() else generic_base_dir()
    os.chdir(base_dir)

    destination = find_iphone_simulator_destination()
    print(f"Using simulator destination: {destination}")

    xcodebuild_command = " ".join(
        [
            "xcodebuild clean build-for-testing",
            "-workspace FacebookSDK.xcworkspace",
            "-scheme BuildAllKits-Dynamic",
            f"-destination 'platform=iOS Simulator,name={destination}'",
        ]
    )

    completed_process = subprocess.run(
        xcodebuild_command, shell=True, check=False, capture_output=True
    )

    output_lines = completed_process.stdout.decode().splitlines()

    warning_lines = {
        line
        for line in output_lines
        if ("warning: " in line or "error: " in line) and not is_diagnostic_context(line)
    }

    # Make the output prettier by removing the base_dir from the warning file paths
    warning_lines = [line.replace(f"{base_dir}/", "") for line in warning_lines]

    non_allowlisted_warnings = []

    for warning in warning_lines:
        can_ignore = any(
            allowed_warning_text in warning
            for allowed_warning_text in XCODEBUILD_WARNINGS_ALLOWLIST
        )
        if not can_ignore:
            non_allowlisted_warnings.append(warning)

    signatures = collections.Counter(normalize(w) for w in non_allowlisted_warnings)

    if args.update_baseline:
        # A failed xcodebuild produces partial output, so the warning set is truncated.
        # Writing that would drop real warnings from the baseline and make the next run
        # report them as new -- breaking every diff until someone regenerated it.
        if completed_process.returncode != 0:
            print_to_stderr(
                f"Refusing to write a baseline: xcodebuild exited "
                f"{completed_process.returncode}, so its output is incomplete."
            )
            print_to_stderr(completed_process.stderr.decode())
            sys.exit(completed_process.returncode)

        # Union by default. Some warnings only appear in one environment -- an SDK header
        # warning surfaced by the build host and not by a laptop, say -- and replacing the
        # file from a local run would silently drop them, so CI would fail on warnings
        # nobody introduced. Shrinking the baseline is deliberate: --prune-baseline.
        existing = load_baseline(base_dir)
        if args.prune_baseline:
            final = collections.Counter(signatures)
            # Drop only what this checkout compiles. Everything external is carried over at
            # its recorded count regardless of whether this run saw it -- see is_external.
            for signature, count in existing.items():
                if is_external(signature):
                    final[signature] = max(final[signature], count)
            dropped = sum(
                1 for s in existing if s not in signatures and not is_external(s)
            )
            preserved = sum(
                1 for s in existing if s not in signatures and is_external(s)
            )
            note = f", dropping {dropped} fixed entry(ies)" if dropped else ""
            if preserved:
                note += f", preserving {preserved} external entry(ies) this run did not see"
        else:
            # Per-signature max, not a sum: re-running must not inflate the counts.
            final = collections.Counter(signatures)
            for signature, count in existing.items():
                final[signature] = max(final[signature], count)
            kept = sum(1 for s in existing if s not in signatures)
            note = f", keeping {kept} entry(ies) not seen in this run" if kept else ""

        path = write_baseline(base_dir, final)
        total = sum(final.values())
        print(f"Wrote {len(final)} warning signature(s) ({total} occurrence(s)) to {path}{note}")
        sys.exit(0)

    baseline = load_baseline(base_dir)

    # Compare occurrence counts, not just presence. A second instance of a warning that is
    # already baselined is still a warning this change introduced.
    new_warnings = sorted(
        f"{signature}   (+{count - baseline.get(signature, 0)}"
        f"{', new' if signature not in baseline else f', was {baseline[signature]}'})"
        for signature, count in signatures.items()
        if count > baseline.get(signature, 0)
    )
    fixed_warnings = sorted(
        f"{signature}   ({baseline[signature]} -> {signatures.get(signature, 0)})"
        for signature in baseline
        if signatures.get(signature, 0) < baseline[signature]
    )

    # Not a failure: a baseline entry that no longer appears means someone fixed it. Say
    # so, so the file gets pruned and the ratchet actually tightens.
    if fixed_warnings:
        print(
            f"\n{len(fixed_warnings)} baseline warning(s) no longer occur. "
            f"Re-run with --update-baseline and land the smaller {BASELINE_FILE}:"
        )
        for i, warning in enumerate(fixed_warnings, start=1):
            print(f"{i}. {warning}")

    if new_warnings:
        warning_count = len(new_warnings)
        warning_word = "WARNINGS" if warning_count > 1 else "WARNING"

        print_to_stderr(f"\nFAILED DUE TO {warning_count} NEW {warning_word}:")
        for i, warning in enumerate(new_warnings, start=1):
            print_to_stderr(f"{i}. {warning}")

        print_to_stderr(
            "\nThese are not in the baseline, so this change introduced them.\n"
            "Fix them, or -- if a warning is unavoidable toolchain noise that can recur\n"
            f"anywhere -- add a pattern to xcodebuild_warnings_allowlist.py. Do not run\n"
            f"--update-baseline to silence a warning you just added; the baseline is for\n"
            "pre-existing debt only."
        )

        sys.exit(1)

    if baseline:
        print(
            f"No new warnings. {len(baseline)} known signature(s) / "
            f"{sum(baseline.values())} occurrence(s) in the baseline."
        )

    if completed_process.returncode != 0:
        print(f"Failed to run xcodebuild. Return code: {completed_process.returncode}")
        print(f"STDERR: {completed_process.stderr.decode()}")
        sys.exit(completed_process.returncode)

    print("Check complete. No unexpected warnings encountered.")
    sys.exit(0)


def is_git_dir():
    return get_output("git rev-parse --is-inside-work-tree") == "true"


def git_base_dir() -> str:
    return get_output("git rev-parse --show-toplevel")


def generic_base_dir() -> str:
    scripts_dir = os.path.dirname(os.path.realpath(__file__))
    return pathlib.Path(scripts_dir).parent.absolute()


def print_to_stderr(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def get_output(command):
    """Returns the output of a shell command"""
    completed_process = subprocess.run(
        command, shell=True, check=False, capture_output=True
    )

    if completed_process.returncode == 0:
        return completed_process.stdout.decode().rstrip()
    else:
        return completed_process.stderr.decode().rstrip()


if __name__ == "__main__":
    main()
