load("@bazel_skylib//lib:dicts.bzl", "dicts")
load("@fbsource//fbobjc/ios-sdk/internal/testing/IpaSizeTestApp:DEFS.bzl", "apple_binary_rule", "apple_bundle_rule", "apple_package_rule")
load("@fbsource//tools/build_defs/apple:fb_apple_resource.bzl", "fb_apple_resource")

fb_apple_resource(
    name = "IpaSizeTestAppResources",
    dirs = [],
    files = glob(["*.png"]),
)

CORE_KIT = "FBSDKCoreKit"

SDK_TYPES = {
    CORE_KIT: [
        "//fbobjc/ios-sdk/FBSDKCoreKit:FBSDKCoreKit",
    ],
    "FBSDKBasics": [
        "//fbobjc/ios-sdk/FBSDKCoreKit_Basics:FBSDKCoreKit_Basics",
    ],
    "FBSDKLoginKit": [
        "//fbobjc/ios-sdk/FBSDKLoginKit:FBSDKLoginKit",
    ],
    "FBSDKShareKit": [
        "//fbobjc/ios-sdk/FBSDKShareKit:FBSDKShareKit",
    ],
}

ALL_DEPENDENCIES = []

[ALL_DEPENDENCIES.extend(SDK_TYPES[sdk]) for sdk in SDK_TYPES]

BUILD_TYPES = dicts.add(
    {sdk: {"deps": SDK_TYPES[sdk]} for sdk in SDK_TYPES},
    {sdk + "_" + CORE_KIT: {"deps": SDK_TYPES[sdk] + SDK_TYPES[CORE_KIT]} for sdk in SDK_TYPES if sdk != CORE_KIT},
    {"NoSDKs": {"deps": []}},
    {"FBSDKAll": {"deps": ALL_DEPENDENCIES}},
)

[apple_package_rule(type) for type in BUILD_TYPES]

[apple_bundle_rule(type) for type in BUILD_TYPES]

[apple_binary_rule(type, BUILD_TYPES) for type in BUILD_TYPES]
