load("@fbsource//tools/build_defs/apple:fb_apple_library.bzl", "fb_apple_library")
load("@fbsource//tools/build_defs/apple:fb_apple_test.bzl", "fb_apple_test")
load("@fbsource//tools/build_defs/apple:flag_defs.bzl", "get_objc_arc_preprocessor_flags", "get_preprocessor_flags_for_build_mode")

# @lint-ignore BUCKLINT
fb_apple_library(
    name = "FBSDKBetaKit",
    bad_practices = ["mixed_module"],
    compiler_flags = [
        "-w",
        "-fembed-bitcode",
        "-Wunused-function",
        "-Werror",
        "-Wincomplete-implementation",
        "-Warc-performSelector-leaks",
    ],
    frameworks = [
        "Accelerate",
        "Foundation",
        "JavaScriptCore",
        "UIKit",
    ],
    labels = ["accounts_for_platform_and_build_mode_flags"],
    link_whole = True,
    modular = True,
    preprocessor_flags = get_objc_arc_preprocessor_flags() + get_preprocessor_flags_for_build_mode(),
    reexport_all_header_dependencies = True,
    tests = [
        "//fbobjc/ios-sdk/internal/FBSDKBetaKit:FBSDKBetaKitTests",
    ],
    deps = [
        "//fbobjc/ios-sdk/FBSDKCoreKit:FBSDKCoreKit",
    ],
)

fb_apple_test(
    name = "FBSDKBetaKitTests",
    autoglob = True,
    bridging_header = "FBSDKBetaKitTests/FBSDKBetaKitTests-Bridging-Header.h",
    compiler_flags = [
        "-w",
        "-fmodules",
    ],
    contacts = ["oncall+platform_sdks@xmail.facebook.com"],
    frameworks = [
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest",
        "Foundation",
    ],
    deps = [
        "//fbobjc/ios-sdk/TestTools:TestTools",
        "//fbobjc/ios-sdk/internal/FBSDKBetaKit:FBSDKBetaKit",
    ],
)
