# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

name: FBSDKBetaKit

include:
  - ../../xcodegen_project_common.yml

projectReferences:

  FBAEMKit:
    path: ../../FBAEMKit/FBAEMKit.xcodeproj
  FBSDKCoreKit_Basics:
    path: ../../FBSDKCoreKit_Basics/FBSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../../FBSDKCoreKit/FBSDKCoreKit.xcodeproj

targets:
  FBSDKBetaKit:
    platform: iOS
    type: framework
    sources:
      - path: FBSDKBetaKit
    configFiles:
      Debug: Configurations/FBSDKBetaKit.xcconfig
      Release: Configurations/FBSDKBetaKit.xcconfig
    dependencies:
      - target: FBAEMKit/FBAEMKit-Static
        embed: false
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Static
        embed: false
      - target: FBSDKCoreKit/FBSDKCoreKit-Static
        embed: false
      - sdk: Accelerate.framework
      - sdk: JavaScriptCore.framework
      - sdk: UIKit.framework
    compilerFlags:
      - "-w"
      - "-Wunused-function"
      - "-Werror"
      - "-Wincomplete-implementation"
      - "-Warc-performSelector-leaks"
  FBSDKBetaKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FBSDKBetaKitTests
    configFiles:
      Debug: Configurations/FBSDKBetaKitTests.xcconfig
    dependencies:
      - target: FBSDKBetaKit
        link: false
        embed: false
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: FBSDKBetaKitTests/FBSDKBetaKitTests-Bridging-Header.h
      GCC_WARN_UNUSED_FUNCTION: NO
