# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:true
  push: https://gezegenonline.com/
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: com.gezegen.com.gezegenonline

    runs-on: macos-latest

    steps: 999999999
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
